# action.yml
name: 'Docker TestRunner'
description: 'Local Docker container to run tests'
inputs:
  image:  # id of input
    required: true
outputs:
  result_output: # id of output
    description: 'Output result of testruns'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.image }}
